trigger:
- main

pool:
  name: WindowVm

jobs:
- job: Build
  displayName: 'Build Job'
  steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '21.0.2'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'

    - task: CopyFiles@2
      inputs:
        Contents: '**/*.jar'
        TargetFolder: '$(build.artifactstagingdirectory)/Artifact'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Artifact'
        publishLocation: 'Container'

- job: Deploy
  displayName: 'Deploy Job'
  dependsOn: Build
  pool:
    name: WindowVm
  steps:
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'Pay-As-You-Go (3f9425f7-b0f9-40b7-9c23-beca0c6a8610)'
        appType: 'webAppLinux'
        appName: 'azure-web-appB2'
        package: '$(System.DefaultWorkingDirectory)/**/*.jar'
        runtimeStack: 'TOMCAT|9.0-java11'
        startupCommand: 'java -jar $(System.DefaultWorkingDirectory)/Artifact/your_actual_jar_file.jar'
