trigger:
- main

pool:
  name: WindowVm

jobs:
- job: Build
  displayName: 'Build Job'
  steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '21.0.2'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'

    - task: CopyFiles@2
      inputs:
        Contents: '$(System.DefaultWorkingDirectory)/**/*.jar'
        TargetFolder: '$(build.artifactstagingdirectory)/Artifact'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Artifact'
        publishLocation: 'Container'

    - task: Docker@2
      inputs:
        containerRegistry: 'AzureDB2Acr'
        repository: 'AzureDB2-image'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'